# Generated by Django 6.0.1 on 2026-02-03 04:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("new_user_platform_invites", models.IntegerField(default=3)),
                ("new_user_discussion_invites", models.IntegerField(default=5)),
                ("responses_to_unlock_invites", models.IntegerField(default=3)),
                ("responses_per_platform_invite", models.IntegerField(default=10)),
                ("responses_per_discussion_invite", models.IntegerField(default=5)),
                ("max_discussion_participants", models.IntegerField(default=10)),
                ("n_responses_before_mrp", models.IntegerField(default=2)),
                ("max_headline_length", models.IntegerField(default=100)),
                ("max_topic_length", models.IntegerField(default=500)),
                (
                    "invite_consumption_trigger",
                    models.CharField(
                        choices=[("sent", "Sent"), ("accepted", "Accepted")],
                        default="accepted",
                        max_length=20,
                    ),
                ),
                (
                    "mrp_calculation_scope",
                    models.CharField(
                        choices=[
                            ("current_round", "Current Round"),
                            ("last_X_rounds", "Last X Rounds"),
                            ("all_rounds", "All Rounds"),
                        ],
                        default="current_round",
                        max_length=20,
                    ),
                ),
                ("mrp_calculation_x_rounds", models.IntegerField(default=3)),
                ("voting_increment_percentage", models.IntegerField(default=20)),
                ("vote_based_removal_threshold", models.FloatField(default=0.5)),
                ("max_discussion_duration_days", models.IntegerField(default=90)),
                ("max_discussion_rounds", models.IntegerField(default=50)),
                ("max_discussion_responses", models.IntegerField(default=500)),
                ("round_1_phase_1_timeout_days", models.IntegerField(default=7)),
                ("allow_duplicate_discussions", models.BooleanField(default=False)),
                ("response_edit_percentage", models.IntegerField(default=20)),
                ("response_edit_limit", models.IntegerField(default=2)),
                ("rtm_min", models.FloatField(default=0.5)),
                ("rtm_max", models.FloatField(default=2.0)),
                ("mrm_min_minutes", models.IntegerField(default=5)),
                ("mrm_max_minutes", models.IntegerField(default=1440)),
                ("mrl_min_chars", models.IntegerField(default=100)),
                ("mrl_max_chars", models.IntegerField(default=5000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform Configuration",
                "verbose_name_plural": "Platform Configuration",
                "db_table": "platform_config",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("platform_invites_acquired", models.IntegerField(default=0)),
                ("platform_invites_used", models.IntegerField(default=0)),
                ("platform_invites_banked", models.IntegerField(default=0)),
                ("discussion_invites_acquired", models.IntegerField(default=0)),
                ("discussion_invites_used", models.IntegerField(default=0)),
                ("discussion_invites_banked", models.IntegerField(default=0)),
                ("is_platform_admin", models.BooleanField(default=False)),
                ("behavioral_flags", models.JSONField(blank=True, default=dict)),
                (
                    "account_deletion_preference",
                    models.CharField(
                        choices=[("delete_all", "Delete All"), ("preserve_data", "Preserve Data")],
                        default="preserve_data",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("topic_headline", models.CharField(max_length=100)),
                ("topic_details", models.TextField(max_length=500)),
                ("max_response_length_chars", models.IntegerField()),
                ("response_time_multiplier", models.FloatField()),
                ("min_response_time_minutes", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delegated_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegated_discussions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_discussions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "discussions",
            },
        ),
        migrations.CreateModel(
            name="DiscussionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("initiator", "Initiator"),
                            ("active", "Active"),
                            ("temporary_observer", "Temporary Observer"),
                            ("permanent_observer", "Permanent Observer"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("observer_since", models.DateTimeField(blank=True, null=True)),
                (
                    "observer_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mrp_expired", "MRP Expired"),
                            ("mutual_removal", "Mutual Removal"),
                            ("vote_based_removal", "Vote Based Removal"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("posted_in_round_when_removed", models.BooleanField(default=False)),
                ("removal_count", models.IntegerField(default=0)),
                ("can_invite_others", models.BooleanField(default=True)),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="core.discussion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "discussion_participants",
            },
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "invite_type",
                    models.CharField(
                        choices=[("platform", "Platform"), ("discussion", "Discussion")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("first_participation_at", models.DateTimeField(blank=True, null=True)),
                (
                    "discussion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="core.discussion",
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "invites",
            },
        ),
        migrations.CreateModel(
            name="JoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("request_message", models.TextField(blank=True)),
                ("response_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests_to_approve",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="core.discussion",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "join_requests",
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_response", "New Response"),
                            ("round_ending_soon", "Round Ending Soon"),
                            ("voting_phase_started", "Voting Phase Started"),
                            ("parameter_changed", "Parameter Changed"),
                            ("became_observer", "Became Observer"),
                            ("can_rejoin", "Can Rejoin"),
                            ("invite_received", "Invite Received"),
                            ("join_request", "Join Request"),
                            ("join_approved", "Join Approved"),
                            ("discussion_archived", "Discussion Archived"),
                        ],
                        max_length=50,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "delivery_method",
                    models.JSONField(default=dict, help_text="JSON with keys: email, push, in_app"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField()),
                ("character_count", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_edited_at", models.DateTimeField(blank=True, null=True)),
                ("edit_count", models.IntegerField(default=0)),
                ("characters_changed_total", models.IntegerField(default=0)),
                ("time_since_previous_minutes", models.FloatField(blank=True, null=True)),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "responses",
            },
        ),
        migrations.CreateModel(
            name="ResponseEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("edit_number", models.IntegerField(choices=[(1, "1"), (2, "2")])),
                ("previous_content", models.TextField()),
                ("new_content", models.TextField()),
                ("characters_changed", models.IntegerField()),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edits",
                        to="core.response",
                    ),
                ),
            ],
            options={
                "db_table": "response_edits",
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("round_number", models.IntegerField()),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("final_mrp_minutes", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("voting", "Voting"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="core.discussion",
                    ),
                ),
            ],
            options={
                "db_table": "rounds",
            },
        ),
        migrations.AddField(
            model_name="response",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="core.round",
            ),
        ),
        migrations.CreateModel(
            name="RemovalVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="removal_votes_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="removal_votes_cast",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="removal_votes",
                        to="core.round",
                    ),
                ),
            ],
            options={
                "db_table": "removal_votes",
            },
        ),
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("mutual_removal", "Mutual Removal"),
                            ("vote_based_removal", "Vote Based Removal"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_permanent", models.BooleanField()),
                ("action_at", models.DateTimeField(auto_now_add=True)),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_actions",
                        to="core.discussion",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_actions_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_actions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "round_occurred",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_actions",
                        to="core.round",
                    ),
                ),
            ],
            options={
                "db_table": "moderation_actions",
            },
        ),
        migrations.CreateModel(
            name="DraftResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "saved_reason",
                    models.CharField(
                        choices=[
                            ("mrp_expired", "MRP Expired"),
                            ("user_saved", "User Saved"),
                            ("round_ended", "Round Ended"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_responses",
                        to="core.discussion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_responses",
                        to="core.round",
                    ),
                ),
            ],
            options={
                "db_table": "draft_responses",
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mrl_vote",
                    models.CharField(
                        choices=[
                            ("increase", "Increase"),
                            ("no_change", "No Change"),
                            ("decrease", "Decrease"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rtm_vote",
                    models.CharField(
                        choices=[
                            ("increase", "Increase"),
                            ("no_change", "No Change"),
                            ("decrease", "Decrease"),
                        ],
                        max_length=20,
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="core.round",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "votes",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone_number"], name="users_phone_n_a3b1c5_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="users_created_6541e9_idx"),
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(
                fields=["status", "created_at"], name="discussions_status_f53808_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(fields=["initiator"], name="discussions_initiat_d35a74_idx"),
        ),
        migrations.AddIndex(
            model_name="discussionparticipant",
            index=models.Index(
                fields=["discussion", "user"], name="discussion__discuss_3158ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discussionparticipant",
            index=models.Index(fields=["user", "role"], name="discussion__user_id_36579b_idx"),
        ),
        migrations.AddIndex(
            model_name="discussionparticipant",
            index=models.Index(
                fields=["observer_since", "observer_reason"], name="discussion__observe_fdf1bc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="discussionparticipant",
            unique_together={("discussion", "user")},
        ),
        migrations.AddIndex(
            model_name="invite",
            index=models.Index(fields=["inviter", "status"], name="invites_inviter_082354_idx"),
        ),
        migrations.AddIndex(
            model_name="invite",
            index=models.Index(fields=["invitee", "status"], name="invites_invitee_6a0333_idx"),
        ),
        migrations.AddIndex(
            model_name="invite",
            index=models.Index(fields=["discussion"], name="invites_discuss_3decd4_idx"),
        ),
        migrations.AddIndex(
            model_name="joinrequest",
            index=models.Index(
                fields=["discussion", "status"], name="join_reques_discuss_15caa6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joinrequest",
            index=models.Index(
                fields=["requester", "status"], name="join_reques_request_fc2676_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(fields=["user", "enabled"], name="notificatio_user_id_4f7e97_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="notificationpreference",
            unique_together={("user", "notification_type")},
        ),
        migrations.AddIndex(
            model_name="responseedit",
            index=models.Index(
                fields=["response", "edited_at"], name="response_ed_respons_8f7ca2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="responseedit",
            unique_together={("response", "edit_number")},
        ),
        migrations.AddIndex(
            model_name="round",
            index=models.Index(
                fields=["discussion", "round_number"], name="rounds_discuss_53bac6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="round",
            index=models.Index(fields=["status"], name="rounds_status_8652fe_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="round",
            unique_together={("discussion", "round_number")},
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(fields=["round", "user"], name="responses_round_i_9e7b23_idx"),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(fields=["created_at"], name="responses_created_616bff_idx"),
        ),
        migrations.AddIndex(
            model_name="removalvote",
            index=models.Index(fields=["round", "voter"], name="removal_vot_round_i_0ec4b5_idx"),
        ),
        migrations.AddIndex(
            model_name="removalvote",
            index=models.Index(fields=["round", "target"], name="removal_vot_round_i_94f68c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="removalvote",
            unique_together={("round", "voter", "target")},
        ),
        migrations.AddIndex(
            model_name="moderationaction",
            index=models.Index(
                fields=["discussion", "action_type"], name="moderation__discuss_5038ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationaction",
            index=models.Index(fields=["initiator"], name="moderation__initiat_35da7c_idx"),
        ),
        migrations.AddIndex(
            model_name="moderationaction",
            index=models.Index(fields=["target"], name="moderation__target__af6152_idx"),
        ),
        migrations.AddIndex(
            model_name="draftresponse",
            index=models.Index(
                fields=["discussion", "round", "user"], name="draft_respo_discuss_9d11c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draftresponse",
            index=models.Index(
                fields=["user", "created_at"], name="draft_respo_user_id_80e336_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["round", "user"], name="votes_round_i_954fbb_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("round", "user")},
        ),
    ]
