# Generated by Django 6.0.1 on 2026-02-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_user_device_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique 8-character invite code (auto-generated)",
                max_length=8,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="invite",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional expiration timestamp for invite code",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="invite",
            index=models.Index(fields=["code"], name="invites_code_d6b44a_idx"),
        ),
    ]
