# Generated by Django 6.0.1 on 2026-02-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_invite_code_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
