# Generated by Django 6.0.1 on 2026-02-05 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_is_draft_to_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
