# Generated by Django 6.0.1 on 2026-02-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_fix_round_start_time_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique 8-character invite code (auto-generated for platform invites)",
                max_length=8,
                null=True,
                unique=True,
            ),
        ),
    ]
