# Generated by Django 6.0.1 on 2026-02-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fix_invite_code_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutorial_completed',
            field=models.BooleanField(default=False),
        ),
    ]
