# Generated by Django 6.0.1 on 2026-02-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_tutorial_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionparticipant',
            name='skip_invite_credits_on_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='discussion_invites_per_response',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='platform_invites_per_response',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='new_user_discussion_invites',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='new_user_platform_invites',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='responses_to_unlock_invites',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='discussion_invites_acquired',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='discussion_invites_banked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='platform_invites_acquired',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='platform_invites_banked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
