# Generated by Django 6.0.1 on 2026-02-06 04:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_join_request_voting"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="joinrequestvote",
            name="unique_join_request_vote",
        ),
        migrations.AlterField(
            model_name="joinrequest",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy field. For voting-based approval, this is null.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_requests_to_approve",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="joinrequestvote",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="voting_credits_awarded",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of user IDs who received voting credits this round",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="joinrequestvote",
            unique_together={("round", "voter", "join_request")},
        ),
    ]
