# Generated by Django 6.0.1 on 2026-02-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_make_join_request_approver_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="voting_credits_awarded",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of user IDs who received voting credits this round",
                null=True,
            ),
        ),
    ]
